version: "3"
services:
  client:
    image: yourapp/client:1.0.0
    ports:
      - "8080:8080"
  server:
    image: yourapp/server:1.0.0
    ports:
      - "3000:3000"
  # Define other services like docs, server_composer, etc.
