version: '3'
services:
  client:
    image: nextjs-docker
    ports:
      - '3000:3000'
    networks:
      - wb-network
    build: ./client
    env_file: ./client/.env

  docs:
    image: docs
    ports:
      - '3001:3001'
    networks:
      - wb-network
    build: ./docs

  worldsbase-server:
    image: worldsbase-server
    ports:
      - '3005:3005'
    networks:
      - wb-network
    build: ./worldsbase-server
    env_file: ./worldsbase-server/.env

networks:
  wb-network:
