version: "3"
services:
  server:
    image: server-docker
    ports:
      - "3003:3003"
    networks:
      - wgs-network
    build: ./server
    env_file: ./server/.env

  client:
    image: nextjs-docker
    ports:
      - "3000:3000"
    networks:
      - wgs-network
    build: ./client
    env_file: ./client/.env

  composer:
    image: composer
    ports:
      - "3008:3008"
    networks:
      - wgs-network
    build: ./server_composer
    env_file: ./server_composer/packages/server/.env

  docs:
    image: docs
    ports:
      - "3001:3001"
    networks:
      - wgs-network
    build: ./docs

  chain:
    image: chain
    ports:
      - "3004:3004"
    networks:
      - wgs-network
    build: ./server_chain
    env_file: ./server_chain/.env

networks:
  wgs-network:
