import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Worlds Dashboard",
  description: "Generated by Worlds Dev Team with Love",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <div style={{ width: "100%" }}>{children}</div>;
}
