import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import { Inter, Lexend } from "next/font/google";
import clsx from "clsx";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Worlds Dashboard",
  description: "Generated by Worlds Dev Team with Love",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(
        "h-full scroll-smooth bg-background antialiased dark ",
        inter.variable,
        lexend.variable
      )}
    >
      <body className="flex flex-col h-full bg-background" id="portal">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
