import Layout from "@/components/layout/Layout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Worlds Dashboard",
  description: "Generated by Worlds Dev Team with Love",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout> {children}</Layout>;
}
