import { ReactNode } from "react";
import type { Metadata } from "next";
import MenuSection from "@/components/dashboard/databasePage/MenuSection";

export const metadata: Metadata = {
  title: "Worlds Dashboard",
  description: "Generated by Worlds Dev Team with Love",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <div className="flex items-center w-full tableFont">
      <div className="hidden bg-green-400 lg:fixed lg:inset-y-0 lg:z-30 lg:flex w-60 lg:flex-col">
        <MenuSection />
      </div>
      <div className="w-full mt-20 overflow-y-auto lg:ml-64">{children}</div>
    </div>
  );
}
